# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - lower_acl_than_parent
  - modifier_order
  - multiline_parameters
  - nimble_operator
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - unavailable_function
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - comma
  - for_where
  - force_cast
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - trailing_comma
  - unused_closure_parameter
  - vertical_whitespace
